# Generated by Django 5.2.9 on 2026-05-07 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('protocolo', models.AutoField(primary_key=True, serialize=False)),
                ('data_atendimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpf_cliente', models.CharField(default='99999999999', max_length=11, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('assunto', models.CharField(choices=[('1', 'JURIDICO'), ('2', 'PESSOAL'), ('3', 'VELÓRIO'), ('4', 'TRANSPORTE'), ('5', 'OUTROS')], default='CE', max_length=20, null=True)),
                ('observacao', models.TextField(blank=True, max_length=300, null=True)),
                ('cod_operador', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('lideranca', models.CharField(max_length=200, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('uf', models.CharField(choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPÁ'), ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARÁ'), ('DF', 'DISTRITO FEDERAL'), ('ES', 'ESPÍRITO SANTO'), ('GO', 'GOIÁS'), ('MA', 'MARANHÃO'), ('MT', 'MATO GROSSO'), ('MS', 'MATO GROSSO DO SUL'), ('MG', 'MINAS GERAIS'), ('PA', 'PARÁ'), ('PB', 'PARAÍBA'), ('PR', 'PARANÁ'), ('PE', 'PERNAMBUCO'), ('PI', 'PIAUÍ'), ('RJ', 'RIO DE JANEIRO'), ('RN', 'RIO GRANDE DO NORTE'), ('RS', 'RIO GRANDE DO SUL'), ('RO', 'RONDÔNIA'), ('RR', 'RORAIMA'), ('SC', 'SANTA CATARINA'), ('SP', 'SÃO PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')], default='CE', max_length=20, null=True)),
                ('fone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('zona', models.CharField(max_length=20, null=True)),
                ('secao', models.CharField(max_length=20, null=True)),
                ('ativo', models.IntegerField(choices=[(1, 'ATIVO'), (2, 'INATIVO')], default=1, null=True)),
                ('dia_aniv', models.IntegerField(default=0)),
                ('mes_aniv', models.IntegerField(default=0)),
                ('ano_aniv', models.IntegerField(default=0)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('cod_operador', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Hist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_id_original', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('lideranca', models.CharField(default='Não informado', max_length=200)),
                ('fone', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPÁ'), ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARÁ'), ('DF', 'DISTRITO FEDERAL'), ('ES', 'ESPÍRITO SANTO'), ('GO', 'GOIÁS'), ('MA', 'MARANHÃO'), ('MT', 'MATO GROSSO'), ('MS', 'MATO GROSSO DO SUL'), ('MG', 'MINAS GERAIS'), ('PA', 'PARÁ'), ('PB', 'PARAÍBA'), ('PR', 'PARANÁ'), ('PE', 'PERNAMBUCO'), ('PI', 'PIAUÍ'), ('RJ', 'RIO DE JANEIRO'), ('RN', 'RIO GRANDE DO NORTE'), ('RS', 'RIO GRANDE DO SUL'), ('RO', 'RONDÔNIA'), ('RR', 'RORAIMA'), ('SC', 'SANTA CATARINA'), ('SP', 'SÃO PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')], default='CE', max_length=20, null=True)),
                ('zona', models.CharField(max_length=20)),
                ('secao', models.CharField(max_length=20)),
                ('ativo', models.IntegerField(default=1)),
                ('dia_aniv', models.IntegerField()),
                ('mes_aniv', models.IntegerField()),
                ('ano_aniv', models.IntegerField()),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('operacao', models.CharField(choices=[('ALTERACAO', 'Alteração'), ('EXCLUSAO', 'Exclusão')], max_length=10)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cod_operador', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('cod_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('protocolo', models.IntegerField()),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=200)),
                ('cod_operador', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
