# Generated by Django 5.2.9 on 2026-05-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_atendimento_cliente_cliente_hist_movimentacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ano_aniv',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dia_aniv',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='mes_aniv',
        ),
        migrations.RemoveField(
            model_name='cliente_hist',
            name='ano_aniv',
        ),
        migrations.RemoveField(
            model_name='cliente_hist',
            name='dia_aniv',
        ),
        migrations.RemoveField(
            model_name='cliente_hist',
            name='mes_aniv',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente_hist',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
