# Generated by Django 5.2.9 on 2026-07-09 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_remove_cliente_ano_aniv_remove_cliente_dia_aniv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_final', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(null=True)),
                ('status_projeto', models.CharField(choices=[('1', 'EM NEGOCIACAO'), ('2', 'AGUARDANDO INICIAR'), ('3', 'EM EXECUCAO'), ('4', 'CONCLUÍDO'), ('5', 'BLOQUEADO')], default='CE', max_length=20, null=True)),
            ],
        ),
    ]
