# Generated by Django 5.2.9 on 2026-07-09 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_projeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status_projeto',
            field=models.CharField(choices=[('1', 'EM NEGOCIACAO'), ('2', 'AGUARDANDO INICIAR'), ('3', 'EM EXECUCAO'), ('4', 'CONCLUÍDO'), ('5', 'BLOQUEADO')], default='1', max_length=20, null=True),
        ),
    ]
