# Generated by Django 5.2.9 on 2026-07-09 23:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_projeto_usuario_alter_projeto_status_projeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_final', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(null=True)),
                ('status_tarefa', models.CharField(choices=[('1', 'EM PLANEJAMENTO'), ('2', 'AGUARDANDO INICIAR'), ('3', 'EM EXECUCAO'), ('4', 'CONCLUÍDO'), ('5', 'BLOQUEADO')], default='1', max_length=20, null=True)),
                ('tipo_tarefa', models.CharField(choices=[('1', 'DOCUMENTAÇÃO'), ('2', 'CÓDIGO'), ('3', 'ANÁLISE'), ('4', 'PLANEJAMENTO'), ('5', 'GESTÃO')], default='1', max_length=20, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
        ),
    ]
