# Generated by Django 5.2.9 on 2026-07-10 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0006_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='cod_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='siteweb.projeto', verbose_name='Projeto'),
        ),
    ]
