# Generated by Django 5.2.9 on 2026-07-10 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0007_tarefa_cod_projeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('grupo', models.CharField(choices=[('1', 'SUPER'), ('2', 'ADM'), ('3', 'USER'), ('4', 'AUDITOR'), ('5', 'CONSULTA')], default='1', max_length=20, null=True)),
                ('papel', models.CharField(choices=[('1', 'DIRETOR'), ('2', 'COORDENADOR'), ('3', 'GESTOR'), ('4', 'PROGRAMADOR'), ('5', 'ANALISTA'), ('6', 'TESTE'), ('7', 'SUPORTE')], default='1', max_length=20, null=True)),
                ('perfil', models.CharField(choices=[('1', 'GESTOR'), ('2', 'EXECUTOR'), ('3', 'GERAL')], default='1', max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Atendimento',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cliente_Hist',
        ),
        migrations.DeleteModel(
            name='Movimentacao',
        ),
    ]
